[bank-statement.tags]
transport = [
"UBER",
"OLA",
"PETROL",
"GRE9WW0FKLBYEB",
"IOCL",
"CRANK MEISTER",
"CAR STEREO",
"TAXI",
"PARKING",
"BIA VENTURES PRIVATE",
"SHOFFR",
"BLU-SMART",
"AKAR SERVICE STATION",
"ADVAITH"
]

groceries = [
"SWIGGY DASH",
"SWIGGY INSTAMART",
"GROFERS",
"BIGBASKET",
"NATURES BASKET",
"NATURESBASKET",
"CARRY FRESH",
"DUNZO",
"ZEPTO",
"THOMS",
"SWIGGYSTORES",
"KIRANA",
"SWEETS",
"KOSHYS",
"D MART",
"GEDDIT",
"COSMIX",
"AKSHAYAKALPA",
"INSTAMART",
"BLINKIT"
]

fnb = [
"WWW.SWIGGY",
"BUNDL TECHNOLOGIES",
"SWIGGY BANGALORE",
"SWIGGY BENGALURU",
"SWIGGY IN GURGAON",
"ARAKU",
"ZOMATO",
"BAR",
"KITCHEN", "WINE",
"FOOD",
"RESTAURANT",
"SHARON",
"JUZI FRUITS",
"FATTY BAO",
"SLYGRANY",
"BRIK OVEN",
"KRISPY KREME",
"BIERE CLUB",
"EATERY",
"THEOBROMA",
"BEER",
"MILANO",
"TYCOONS",
"PIZZA",
"SLYGRANNY",
"LAVONNE",
"MAVERICK AND FARMER",
"FROTHY TALES",
"BOTECO",
"SHILTON",
"THINDIS",
"COFFEE",
"PRASHANT ROL",
"TEA",
"MOMOS",
"MOMO",
"CORN",
"CHAI",
"BEGUM VICTORIA",
"CAFE",
"JUICE",
"STARBUCKS",
"V ANDRO HOSPITALITY", # tycoons
"SUNNYS",
"CONCU",
"SWIGGY IN BANGALORE",
"BACKER DEUTSCHLAND",
"SWIGGY LIMITED",
"BISTRO",
"CHOTA SWAAD"
]

donations = [
"WIKIMEDIA",
"MILAAP",
"UNICEF",
"FROM KITTY",
"VIPASSANA"
]

tax = [
"CBDT",
"ITDTAX"
]

whitecollarservices = [
"FINMOJO",
"PARIVARTHAN"
]

subscriptions = [
"NETFLIX",
"APPLE",
"MYGIFTCARD",
"NINTENDO",
"GOOGLE",
"SPOTIFY",
"YOUTUBE",
"NYTIMES",
"DIGITALOCEAN",
"RENDER.COM",
"FLOWLYF",
"RENTOMOJO",
"OPENAI",
"MIDJOURNEY",
"GITHUB",
"GREEN GOAT GAMING",
"SUPERMAVEN",
"HOTSTAR",
"STRAVA",
"FASTMAIL"
]

pets = [
"EARTH PAW",
"HEADS UP FOR TAILS",
"CESSNA",
"HUFT",
"PETS",
"PET"
]

investments = [
"MF",
"CLEARING",
"LIC",
"ACH",
"FD ",
"BAJAJFINANCE",
"BAJAJ FINANCE",
"RELIANC",
"D4GGOAUY2H7SWA",
"PPF",
"00602300000434-019578064",
"GIFT",
"TPT-STONKS",
"HSL SEC",
"SHRIRAMTRANSPORT",
"ZERODHA",
"PRIN AND INT AUTO_REDEEM",
"INT. AUTO_REDEMPTION",
"RFX",
"LIFE IN",
"MUTUAL FUND",
"50200021339924",
"SHRIRAM FINANCE",
"TATA CAP HSG NCD",
"HDFC SECURITIES"
]

household = [
"URBAN COMPANY",
"URBANCLAP",
"BROADBAND",
"BBMP",
"ELECTRICITY",
"DOVES NEST",
"POSTPAID",
"SBIN0040199",
"IQBAL AHMED",
"SUMITHRA",
"AIRTEL",
"SMART AIR FILTERS",
"SAMUEL",
"CLEANERS",
"CLEANING",
"URBANMALI",
"DYSON",
"EMBER",
"EUREKA FORBES",
"ATOMBERG"
]

salary-reimbursement = [
"NILENSO",
"USD2800",
"USD1700",
"USD1500",
"USD1800",
"USD2000",
"USD 2000",
"USD315",
"USD1685",
"USD105.0",
"INW"
]

medicines = [
"APOLLO",
"MEDICAL",
"COLUMBIA ASIA",
"PRACTO",
"PHYSIO",
"HEALTH",
"MOONCUP",
"DIAGNOSTIC",
"DENTAL",
"MOSAIC WELLNESS",
"MANIPAL HOSPITALS",
"CHEMIST",
"PHARMA"
]

shopping = [
"AMAZON",
"FLIPKART",
"PAYPAL",
"RETRO DAYS",
"RETAIL",
"MALL",
"SHOP",
"COSMETICS",
"MYLEE",
"HENNES N MAURITZ",
"HIGH GLOSS",
"SHADES OF SPRING",
"NO NASTIES",
"AJIO",
"JAYPORE",
"DECATHLON",
"FLOWLY",
"NAZARETH",
"SMOOKAH",
"DREAMPLUG",
"MOUNTAIN VALLEY SPRINGS",
"BIRKENSTOCK",
"MAN MATTERS",
"ANGRAKHAA",
"MINIMALIST",
"DAILYOBJECTS",
"SAPNA"
]

credit-card = [
"CC",
"CRED"
]

cash = [
"NWD",
"EAW"
]

travel = [
"CLEARTRIP",
"HOTEL",
"LOUNGE",
"AIRLINES",
"MAKEMYTRIP",
"IRCTC",
"IMMIGRATION",
"VFSGLOBAL",
"INDIAN RAILWAY",
"AIR INDIA",
"GARDENIA",
"THOMAS COOK",
"AKSHAY GUPTA-NIYO8553427344"
]

fitness = [
"OUTFIT",
"GYM",
"RUNNING",
"S AND S INTERBUILD",
"PLAYO"
]

renovation = [
"MARUTHI CERAMICS",
"HOMECENTRE",
"KOHLER",
"WELDING",
"FDRL0001535",
"KHUS",
"IKEA"
]

entertainment = [
"PVR",
"WASTELAND ENTERTAINMEN",
"SKILLBOX"
]

[bank-statement.filters]
debit = [
"CLEARING",
"LIC",
"NEW FD",
"CBDT",
"BAJAJFINANCE",
"BAJAJ FINANCE",
"RELIANC",
"D4GGOAUY2H7SWA",
"PPF",
"FD THROUGH NET",
"GIFT",
"STONKS",
"HSL SEC",
"SHRIRAMTRANSPORT",
"ZERODHA",
"RFX",
"LIFE IN",
"50200021339924",
"SHRIRAM FINANCE"
]

credit = [
"FD PREMAT",
"MUTUAL FUND",
"MF",
"NILENSO",
"BDCP",
"AUTO_REDE",
"ACH",
"SWEEP-IN",
"USD2800",
"USD1700",
"USD1500",
"USD1800",
"USD2000",
"USD 2000",
"USD1685",
"USD315",
"00602300000434-019578064",
"ITDTAX",
"PRIN AND INT AUTO_REDEEM",
"INT. AUTO_REDEMPTION",
"SHRIRAM FINANCE",
"TATA CAP HSG NCD",
"INW"
]
